### ISSUE TITLE
Stratification for user datasets

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#10]

**Comment by santoshkaranam** [comment]
This issue is a duplicate of #8

**Comment by kvantricht** [comment]
Waiting for the fast API scripts from @cbutsko .

**Comment by cbutsko** [comment]
The API call is implemented here https://github.com/WorldCereal/worldcereal-referencedata/blob/main/harmonization/main.py
waiting for testing/deployment from IASA side
