### ISSUE TITLE
RDM DDF input

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#14]
Provide input to design of RDM in next two weeks, so VITO can review!

**Comment by santoshkaranam** [comment]
https://vitoresearch.sharepoint.com/:w:/r/sites/21717-ccn-world-cereal/Shared%20Documents/General/Deliverables/D05-DDF/D05-DDF_WorldCerealPhaseII_V0.1.docx?d=wb3cba63b9a9b484d8fad0fb464fc2c26&csf=1&web=1&e=soofdo
