### ISSUE TITLE
temporary page to explain how to publish data

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#17]
Add a placeholder page that says to contact moderator to help with publishing data.
Will be removed when full instructions are in place.

**Comment by santoshkaranam** [comment]
raised a ticket with IIASA ICT to create a mail list

**Comment by santoshkaranam** [comment]
ewoc-rdm@iiasa.ac.at mail list created with following emails
1. karanam@iiasa.ac.at
2. lasobaya@iiasa.ac.at
3. hendrik.boogaard@wur.nl
4. arun.pratihast@wur.nl
5. jeroen.degerickx@vito.be
6. kristof.vantricht@vito.be


can add more emails if needed.
