### ISSUE TITLE
RDM: export samples selected for cal/val to geoparquet

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#6]
Stratification runs will select a subset of the full sample database.
We would like to export this to geoparquet. This can be one geoparquet file per stratification identifier.

The geoparquet should be available on public http url, can be a signed url.

This should then allow processing module to retrieve samples by: stratification id + ref/collection id + h3 index + timestamp (optional)

**Comment by santoshkaranam** [comment]
samples for each dataset can be downloaded from url /collections/{collectionId}/sample/download. Additionally if re sampling is done, then new geoparquets can be generated by bassing additional query parameter.

This is available for public datasets.
For user private datasets, signed urls to geoparquets can be generated,
