### ISSUE TITLE
RDM: automated stratification of user datasets

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#8]
- [ ] automatically run stratification script
- [ ] generate geoparquet file, if openEO requires separate file (TBD)

**Comment by santoshkaranam** [comment]
First version completed, need to be reviewed
https://github.com/WorldCereal/worldcereal-referencedata/blob/main/harmonization/extraction_flag.py

Pending
- [x] 1. Review of the code
- [x] 2. Convert to docker image
- [x] 3. Host Service inside RDM

**Comment by santoshkaranam** [comment]
@cbutsko  is currently working on converting script to service using FastAPI

**Comment by santoshkaranam** [comment]
@cbutsko has provided the first version of scripts to assign h3 index, extract samples and also mapping suggestions.  I will test this and integrate

**Comment by santoshkaranam** [comment]
service deployed, need to trigger stratification based on criteria.

**Comment by santoshkaranam** [comment]
@ this is done. When user dataset is uploaded, h3 indexes are assigned and stratified to mark subset of samples as extract=1.

issue can be closed
